name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup tree-sitter
        uses: tree-sitter/setup-action@v1
      - name: Run linter
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
          lint: true
          test-grammar: false
          test-library: false

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            ext: dylib
            cc: cc
          - os: ubuntu-latest
            ext: so
            cc: cc
          - os: windows-latest
            ext: dll
            cc: x86_64-w64-mingw32-gcc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup tree-sitter
        uses: tree-sitter/setup-action@v1
        with:
          install-lib: false
      - name: Build and test
        run: npm run-script build-test
      - name: Check unchanged parser
        shell: bash
        run: |
          git status
          exit $(git status --porcelain=v1 2>/dev/null | grep -c src/parser.c)
      - name: Build lib
        run: |
          ${{ matrix.cc }} -fPIC -c -Isrc/ src/parser.c -o parser.o
          ${{ matrix.cc }} -fPIC -shared parser.o -o libtree-sitter-magik.${{ matrix.ext }}
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: libtree-sitter-magik-${{ runner.os }}
          path: libtree-sitter-magik*
          if-no-files-found: error
